-- Registry + audit log for standalone DATASUS .dbc -> consolidated .parquet converter.
-- Naming: LOG_ tables + column prefixes (aligned with downloader / converterCSV scripts).
-- Target: SQL Server.
-- Run: sqlcmd -S <server> -d BR_DATASUS_DB -i Create-Tables-ConverterParquet.sql

IF OBJECT_ID(N'dbo.LOG_DATASUS_DBC_PARQUET_RUN', N'U') IS NOT NULL
    DROP TABLE dbo.LOG_DATASUS_DBC_PARQUET_RUN;
GO

IF OBJECT_ID(N'dbo.LOG_DATASUS_DBC_PARQUET_ARTIFACT', N'U') IS NOT NULL
    DROP TABLE dbo.LOG_DATASUS_DBC_PARQUET_ARTIFACT;
GO

IF OBJECT_ID(N'dbo.LOG_DATASUS_DBC_PARQUET_ARTIFACT', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LOG_DATASUS_DBC_PARQUET_ARTIFACT (
        ID_LOG_DATASUS_DBC_PARQUET_ARTIFACT UNIQUEIDENTIFIER NOT NULL
            CONSTRAINT DF_LOG_DATASUS_DBC_PARQUET_ARTIFACT_ID DEFAULT (NEWSEQUENTIALID()),
        DC_OUTPUT_PATH              NVARCHAR(2000) NOT NULL,
        CD_CATALOG                    NVARCHAR(8)    NOT NULL,
        CD_STATE                      NVARCHAR(8)    NOT NULL,
        NR_FILE_YEAR                  SMALLINT       NOT NULL,
        NR_FILE_MONTH                 TINYINT        NOT NULL,
        DC_LOGICAL_BASE               NVARCHAR(16)   NOT NULL,
        BN_INPUT_FINGERPRINT_SHA256   CHAR(64)       NOT NULL,
        BN_PARQUET_SHA256_HEX         CHAR(64)       NULL,
        DC_LAST_STATUS                NVARCHAR(32)   NOT NULL,
        DC_LAST_ERROR                 NVARCHAR(4000) NULL,
        DT_UPDATED_UTC                DATETIME2(3)   NOT NULL
            CONSTRAINT DF_LOG_DATASUS_DBC_PARQUET_ARTIFACT_UPDATED DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_LOG_DATASUS_DBC_PARQUET_ARTIFACT PRIMARY KEY (ID_LOG_DATASUS_DBC_PARQUET_ARTIFACT),
        CONSTRAINT UQ_LOG_DATASUS_DBC_PARQUET_ARTIFACT_OUTPUT UNIQUE (DC_OUTPUT_PATH)
    );

    CREATE INDEX IX_LOG_DATASUS_DBC_PARQUET_ARTIFACT_KEY
        ON dbo.LOG_DATASUS_DBC_PARQUET_ARTIFACT (CD_CATALOG, CD_STATE, NR_FILE_YEAR, NR_FILE_MONTH, DC_LOGICAL_BASE);
END
GO

IF OBJECT_ID(N'dbo.LOG_DATASUS_DBC_PARQUET_RUN', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LOG_DATASUS_DBC_PARQUET_RUN (
        ID_LOG_DATASUS_DBC_PARQUET_RUN UNIQUEIDENTIFIER NOT NULL
            CONSTRAINT DF_LOG_DATASUS_DBC_PARQUET_RUN_ID DEFAULT (NEWSEQUENTIALID()),
        DT_ATTEMPT_STARTED_UTC       DATETIME2(3)   NOT NULL,
        DT_ATTEMPT_FINISHED_UTC      DATETIME2(3)   NULL,
        DC_OUTPUT_PATH               NVARCHAR(2000) NOT NULL,
        IC_SUCCESS                   BIT            NOT NULL,
        DC_ERROR_MESSAGE             NVARCHAR(4000) NULL,
        QT_DATA_ROWS                 BIGINT         NULL,
        DC_SOURCE_PATHS_JSON         NVARCHAR(MAX)  NULL,
        BN_INPUT_FINGERPRINT_SHA256  CHAR(64)       NULL,
        BN_OUTPUT_PARQUET_SHA256_HEX CHAR(64)       NULL,
        CONSTRAINT PK_LOG_DATASUS_DBC_PARQUET_RUN PRIMARY KEY (ID_LOG_DATASUS_DBC_PARQUET_RUN)
    );

    CREATE INDEX IX_LOG_DATASUS_DBC_PARQUET_RUN_PATH_TIME
        ON dbo.LOG_DATASUS_DBC_PARQUET_RUN (DC_OUTPUT_PATH, DT_ATTEMPT_STARTED_UTC DESC);
END
GO
