-- Registry + audit log for standalone DATASUS .dbc FTP downloader.
-- Naming: NDRS-style LOG_ tables + column prefixes (see DATASUS repo ndrs-sqlserver-conventions).
-- Target: SQL Server (e.g. azwladatasus01d / BR_DATASUS_DB).
-- Run: sqlcmd -S <server> -d BR_DATASUS_DB -i Create-Tables-Datasus-Dbc-Download-Registry.sql
--
-- EX_FTP_REMOTE_PATH is NVARCHAR(512) so UNIQUE(DC_FTP_HOST, EX_FTP_REMOTE_PATH) stays within
-- SQL Server's 1700-byte nonclustered index key limit.

IF OBJECT_ID(N'dbo.DatasusDbcDownloadLog', N'U') IS NOT NULL
    DROP TABLE dbo.DatasusDbcDownloadLog;
IF OBJECT_ID(N'dbo.DatasusDbcFile', N'U') IS NOT NULL
    DROP TABLE dbo.DatasusDbcFile;
GO

IF OBJECT_ID(N'dbo.LOG_DATASUS_DBC_FILE', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LOG_DATASUS_DBC_FILE (
        ID_LOG_DATASUS_DBC_FILE UNIQUEIDENTIFIER NOT NULL
            CONSTRAINT DF_LOG_DATASUS_DBC_FILE_ID DEFAULT (NEWSEQUENTIALID()),
        DC_FTP_HOST             NVARCHAR(260)    NOT NULL,
        EX_FTP_REMOTE_PATH      NVARCHAR(512)    NOT NULL,
        DC_FTP_DIRECTORY        NVARCHAR(1000)   NOT NULL,
        DC_FILE_NAME            NVARCHAR(260)    NOT NULL,
        CD_CATALOG              NVARCHAR(8)      NULL,
        CD_STATE                NVARCHAR(8)      NULL,
        NR_FILE_YEAR            SMALLINT         NULL,
        NR_FILE_MONTH           TINYINT          NULL,
        CD_SEGMENT              NCHAR(1)         NULL,
        QT_REMOTE_SIZE_BYTES    BIGINT           NOT NULL,
        DT_REMOTE_MODIFIED_UTC  DATETIME2(3)     NULL,
        DC_LOCAL_PATH           NVARCHAR(2000)   NULL,
        QT_LOCAL_SIZE_BYTES     BIGINT           NULL,
        BN_LOCAL_SHA256_HEX     CHAR(64)         NULL,
        DT_LAST_DOWNLOAD_UTC    DATETIME2(3)     NULL,
        DC_LAST_DOWNLOAD_STATUS NVARCHAR(32)     NULL,
        NR_DOWNLOAD_COUNT       INT              NOT NULL
            CONSTRAINT DF_LOG_DATASUS_DBC_FILE_DL_COUNT DEFAULT (0),
        DT_CREATED_UTC          DATETIME2(3)     NOT NULL
            CONSTRAINT DF_LOG_DATASUS_DBC_FILE_CREATED DEFAULT (SYSUTCDATETIME()),
        DT_UPDATED_UTC          DATETIME2(3)     NOT NULL
            CONSTRAINT DF_LOG_DATASUS_DBC_FILE_UPDATED DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_LOG_DATASUS_DBC_FILE PRIMARY KEY (ID_LOG_DATASUS_DBC_FILE),
        CONSTRAINT UQ_LOG_DATASUS_DBC_FILE_HOST_PATH UNIQUE (DC_FTP_HOST, EX_FTP_REMOTE_PATH)
    );

    CREATE INDEX IX_LOG_DATASUS_DBC_FILE_CATALOG_PERIOD
        ON dbo.LOG_DATASUS_DBC_FILE (CD_CATALOG, NR_FILE_YEAR, NR_FILE_MONTH)
        INCLUDE (DC_FILE_NAME, DT_LAST_DOWNLOAD_UTC);
END
GO

IF OBJECT_ID(N'dbo.LOG_DATASUS_DBC_DOWNLOAD', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LOG_DATASUS_DBC_DOWNLOAD (
        ID_LOG_DATASUS_DBC_DOWNLOAD UNIQUEIDENTIFIER NOT NULL
            CONSTRAINT DF_LOG_DATASUS_DBC_DOWNLOAD_ID DEFAULT (NEWSEQUENTIALID()),
        ID_LOG_DATASUS_DBC_FILE     UNIQUEIDENTIFIER NOT NULL,
        DT_ATTEMPT_STARTED_UTC      DATETIME2(3)     NOT NULL,
        DT_ATTEMPT_FINISHED_UTC     DATETIME2(3)     NULL,
        DC_FTP_HOST                 NVARCHAR(260)    NOT NULL,
        EX_FTP_REMOTE_PATH          NVARCHAR(512)    NOT NULL,
        QT_REMOTE_SIZE_BYTES        BIGINT           NOT NULL,
        DT_REMOTE_MODIFIED_UTC      DATETIME2(3)     NULL,
        DC_TRIGGER_REASON           NVARCHAR(64)     NOT NULL,
        IC_SUCCESS                  BIT              NOT NULL,
        DC_ERROR_MESSAGE            NVARCHAR(4000)   NULL,
        DC_LOCAL_PATH               NVARCHAR(2000)   NULL,
        QT_LOCAL_SIZE_BYTES         BIGINT           NULL,
        CONSTRAINT PK_LOG_DATASUS_DBC_DOWNLOAD PRIMARY KEY (ID_LOG_DATASUS_DBC_DOWNLOAD),
        CONSTRAINT FK_LOG_DATASUS_DBC_DOWNLOAD_FILE
            FOREIGN KEY (ID_LOG_DATASUS_DBC_FILE) REFERENCES dbo.LOG_DATASUS_DBC_FILE (ID_LOG_DATASUS_DBC_FILE)
    );

    CREATE INDEX IX_LOG_DATASUS_DBC_DOWNLOAD_FILE_TIME
        ON dbo.LOG_DATASUS_DBC_DOWNLOAD (ID_LOG_DATASUS_DBC_FILE, DT_ATTEMPT_STARTED_UTC DESC);
END
GO
